### ISSUE TITLE
Droidcam drivers interfere with Windows drivers

### ISSUE THREAD

**Issue by SaurabhPGunjal** [aramg/droidcam#101]
After installing the desktop client. My brightness and volume keys worked but they no longer showed the sliders on the screen when pressed. Media keys (Play, Pause, Next, Previous) stopped working completely. 

I disabled the Droidcam drivers from video/audio section of drivers in device manager and everything worked fine.

I'm using Win 10 on Lenovo Ideapad S340

**Comment by aramg** [comment]
Closing as off-topic, since this repo hosts the linux client.

Unfortunately it would be near impossible for me to debug this for you, and there have been no other similar reports. 
You can keep the drivers disabled and use "Source 2" which is not a full blown driver and should no interfere with anything,
