### ISSUE TITLE
Fail to link client

### ISSUE THREAD

**Issue by dcesari** [aramg/droidcam#5]
After some modifications to the makefile (see my answer to #4), the client sources compile on Fedora 20, but fail to link with the error:
```
decoder.o: In function `decode_next_frame':
decoder.c:(.text+0xaa5): undefined reference to `jpeg_mem_src_tj'
collect2: error: ld returned 1 exit status
```
the `jpeg_mem_src_tj` function is declared in decoder.c but defined nowhere, is there anything missing?

The kernel module compiles and works, the binary clients from dev47apps.com work as well.

**Comment by aramg** [comment]
Hi,
You want libjpeg-turbo [1]. I think there are 2 "turbo" libs with, making it a little confusing.
`$ grep jpeg_mem_src_tj libjpeg-turbo/*.c
libjpeg-turbo/jdatasrc-tj.c:jpeg_mem_src_tj (j_decompress_ptr cinfo,`

[1] https://sourceforge.net/projects/libjpeg-turbo/

**Comment by dcesari** [comment]
Thanks, I had a look more in detail, I think it depends on how the shared library is built within libjpeg-turbo, the symbol `jpeg_mem_src_tj` is made local in the .so, thus becoming invisible; if I link with the static library .a or with the object file `jpeg_mem_src_t.o` everything works, however I cannot explain why.

**Comment by aramg** [comment]
Right, I see. 'jpeg_mem_src_t.o' must be missing in the .so linker line maybe.
So everything compiles now?

**Comment by dcesari** [comment]
Yes, it compiles, thanks!

**Comment by morsik** [comment]
This is quite old, but… still valid. I cannot build this on Fedora 31 (I did fixes from #4 manually even before finding this thread), but there are no static libraries in Fedora 31 anymore :( Only shared.

I guess this should be developer bug - since this symbol is not made public it shouldn't be used by droidcam? Is there something we can do with this without building whole libjpeg-turbo alongside this small application?

**Comment by aramg** [comment]
Thanks, I'll make a note to review dependencies (the build is VERY outdated) along with #13 .

**Comment by GabVenturato** [comment]
Hi, actually I am trying to compile droidcam in Fedora 31 too. I've managed to include libraries. But now I am stuck with these errors:

```
/usr/bin/ld: /tmp/cc6W6Ace.o: in function `decoder_prepare_video':
decoder.c:(.text+0x839): undefined reference to `sws_getCachedContext'
/usr/bin/ld: /tmp/cc6W6Ace.o: in function `decoder_cleanup':
decoder.c:(.text+0xa0c): undefined reference to `sws_freeContext'
/usr/bin/ld: /tmp/cc6W6Ace.o: in function `decode_next_frame':
decoder.c:(.text+0xa8a): undefined reference to `jpeg_mem_src_tj'
/usr/bin/ld: /tmp/cc6W6Ace.o: in function `decoder_share_frame':
decoder.c:(.text+0x1808): undefined reference to `sws_scale'
```
Do you have any guess?

What I've done is to install the following dependencies:
```
speex-devel
speexdsp-devel
libjpeg-turbo-utils
ffmpeg-devel
```
And then I've modified the makefile LIB in this way:
`LIBS     = -lgthread-2.0 -I/usr/include/ffmpeg/ -L/usr/lib -ljpeg`

Moreover I had to change `PIX_FMT_YUV420P` in `decoder.c` into `AV_PIX_FMT_YUV420P` as suggested from the compiler. But I didn't do any ruther search about why.

**Comment by morsik** [comment]
Ok, I was able to run DroidCam/DroidCamX with another hackery using https://github.com/umlaeute/v4l2loopback which works on current kernel and magic ffmpeg command (:D) which connects to DroidCam MJPEG stream and pushes it to `/dev/videoX`. So basically does the same job as this client application does except no GUI and need to make resolution very specific.

After compiling mentioned v4l2loopback, load module with specific resolution:
```
sudo modprobe v4l2loopback card_label="PhoneScreen" video_nr=9 max_width=1280 max_height=720
```

And then run ffmpeg:
```
ffmpeg -i 'http://192.168.55.106:4747/video?1280x720' -f v4l2 -filter_complex "nullsrc=size=1280x720, format=yuv420p [base];   [0:v] format=pix_fmts=yuv420p, setpts=PTS-STARTPTS, scale=1280x720 [left]; [base][left] overlay=shortest=1,format=yuv420p"   /dev/video9
```

Make sure what resolution matches everywhere or you'll get corrupted image.

@aramg maybe think about removing this kernel module at all then since there is working one for loopback device and maybe migrating even directly to ffmpeg since it works?

The problem I found with this solution: I wasn't able to use "Connect to PC Server" in DroidCamX. It looks like it sends some connection request to client application - which ffmpeg in listen mode (`ffmpeg -rtsp_flags listen -f mjpeg -i 'http://0.0.0.0:4747/'`) doesn't recongnize and DroidCamX just shows error about "Read timed out".

**Comment by morsik** [comment]
Just saw @pdvrieze Merge Request… it builds without problem, but it misses most important part ;) The Makefile changes:

```diff
-LIBS     = -lgthread-2.0 -l:/usr/lib/libswscale.a  -l:/usr/lib/libavutil.a -l:/opt/libjpeg-turbo/lib`getconf LONG_BIT`/libturbojpeg.a -I/usr/include/ffmpeg
+LIBS     = -lgthread-2.0 -lswscale -ljpeg -I/usr/include/ffmpeg
```

This is I've done on my Fedora.

**Comment by GabVenturato** [comment]
@morsik you should look at both pull request from @pdvrieze (and maybe also at mine). However, if you solved compiling problems, I think it is better to open a new separate issue :)

**Comment by morsik** [comment]
@GabVenturato yep, I guess so I'll create just new issue.
