### ISSUE TITLE
[Feature Request] macOS Client

### ISSUE THREAD

**Issue by chromer030** [aramg/droidcam#53]
Hey , Thank you very much for this great tool.
Can we expect macOS support in future releases ?
Thanks again.

**Comment by aramg** [comment]
Yep, I have the MacOS drivers, now I just need to hook it all up with the apps. Will try to prioritize that soon. 

Will be announced on Twitter, but I'll leave this issue open until then as well.

**Comment by chromer030** [comment]
Very Good News , This app is unique... Thank you...

**Comment by ewagner12** [comment]
Hi, thank you for the great app! Let me know if you need beta (or alpha) testers. My Macbook is ready.

**Comment by aramg** [comment]
Unfortunately I'm going to have to close this.

I got a prototype Mac client built with a contractor a while back - but due to restrictions on macOS, the client performance and architecture were not to my liking at all. 

Combined with the signing fiasco back in May, [support for virtual cams is still not consistent](https://github.com/johnboiles/obs-mac-virtualcam/wiki/Compatibility).

Overall, the mac client was not something I was comfortable releasing and supporting, and it was never finished.
Soon OBS Studio for Mac will add a virtual cam, and it will be possible to use the new DroidCam OBS app with it.
