### ISSUE TITLE
Use v4l2loopback upstream kernel module

### ISSUE THREAD

**Issue by invidian** [aramg/droidcam#56]
Packaging/architecture questions here:
- Why does `droidcam` require it's own kernel module? From security point of view, this seems suspicious, that application brings it's own kernel module.
- Why upstream https://github.com/umlaeute/v4l2loopback couldn't be used? I think this would simplify the maintenance work, as well as packaging, as `v4l2loopback` is already available for several distros (e.g. Arch, Ubuntu). Are there some specific changes done to this module, which e.g. has been rejected by upstream?

**Comment by aramg** [comment]
v4l2loopback was forked in 2013 for droidcam, primarily because:
(1) I wanted the webcam to report itself as "DroidCam" for UX
(2) I wanted the webcam to work (be blank) even if the client isnt running
(3) Back then v4l2loopback wasn't as widely available IIRC

I'm open to deprecating this old fork, especially if v4l2loopback get accepted into the kernel
https://github.com/umlaeute/v4l2loopback/issues/268#issuecomment-623856066
